/** Публичные пути к ассетам блока Offer (`public/images/offer/`). */
export const OFFER_PATTERN_MOBILE = '/images/offer/Pattern.png'
export const OFFER_PATTERN_TABLET = '/images/offer/Pattern768.png'
export const OFFER_MASCOT_MOBILE = '/images/offer/mascot.png'
export const OFFER_MASCOT_TABLET = '/images/offer/mascot-768.png'
export const OFFER_MASCOT_WIDE = '/images/offer/mascot-1024.png'
export const OFFER_PATTERN_WIDE = '/images/offer/Pattern1024.png'
export const OFFER_MASCOT_LAPTOP = '/images/offer/mascot-1280.png'
export const OFFER_PATTERN_LAPTOP = '/images/offer/Pattern1280.png'
export const OFFER_MASCOT_DESKTOP = '/images/offer/mascot-1600.png'
export const OFFER_PATTERN_DESKTOP = '/images/offer/Pattern1600.png'
export const OFFER_MASCOT_DESKTOP_XL = '/images/offer/mascot-1920.png'
export const OFFER_PATTERN_DESKTOP_XL = '/images/offer/Pattern1920.png'
